# .github/workflows/review.yml

# Workflow name
name: "Review"

# Event for the workflow
on:
  pull_request:
    branches:
      - develop
      - master

# List of jobs
jobs:
  build:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
